// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.



class Solution {
    public char findTheDifference(String s, String t) {
       // this is my brute force//
    //     StringBuilder sb=new StringBuilder(t);
    //     for(char ch:s.toCharArray()){
    //         int idx=sb.indexOf(String.valueOf(ch));
    //        sb.deleteCharAt(idx); 
    //     }
    //    return sb.charAt(0);
    char res=0;
    for(char ch:s.toCharArray()) res^=ch;
    for(char ch:t.toCharArray()) res^=ch;
    return res;
    }
}